//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JWL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Good
    {
        public int ID { get; set; }
        public int UID { get; set; }
        public string Title { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<double> Size { get; set; }
        public string SrcAddress { get; set; }
        public string SrcAddressDetail { get; set; }
        public string DestAddress { get; set; }
        public string DestAddressDetail { get; set; }
        public Nullable<System.DateTime> SendTime { get; set; }
        public Nullable<System.DateTime> ReachTime { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<bool> IsDel { get; set; }
    
        public virtual User User { get; set; }
    }
}
