//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JWL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lorry
    {
        public Lorry()
        {
            this.Trends = new HashSet<Trend>();
        }
    
        public string No { get; set; }
        public Nullable<int> LorryType { get; set; }
        public Nullable<double> LorryLength { get; set; }
        public Nullable<double> CarryWeight { get; set; }
        public Nullable<int> DriverId { get; set; }
        public string Pic { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<Trend> Trends { get; set; }
    }
}
