//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JWL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Summary { get; set; }
        public string Html { get; set; }
        public Nullable<int> Author { get; set; }
        public string Pics { get; set; }
        public string ComeFrom { get; set; }
        public string ComeFromUrl { get; set; }
        public Nullable<int> Tags { get; set; }
        public Nullable<int> Applaud { get; set; }
        public Nullable<int> Tread { get; set; }
        public Nullable<int> Click { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<bool> IsDel { get; set; }
    }
}
