//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JWL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trend
    {
        public int ID { get; set; }
        public string LorryNo { get; set; }
        public string SrcAddress { get; set; }
        public string DestAddress { get; set; }
        public Nullable<System.DateTime> DepartureTime { get; set; }
        public Nullable<System.DateTime> ReachTime { get; set; }
        public Nullable<System.DateTime> GoBackTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string CurrentCity { get; set; }
    
        public virtual Lorry Lorry { get; set; }
    }
}
