//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JWL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Type
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string CodeName { get; set; }
        public string KeyWord { get; set; }
        public Nullable<int> FID { get; set; }
        public Nullable<int> SubType { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
